baseURL = "http://blog.bdser.cc/"
# 更改使用 Hugo 构建网站时使用的默认主题
theme = "DoIt"

# 网站标题
title = "道草站点"
# 网站语言, 仅在这里 CN 大写 ["en", "zh-CN", "fr", "pl", ...]
languageCode = 'zh-CN'
# 语言名称 ["English", "简体中文", "Français", "Polski", ...]
languageName = "简体中文"
# 是否包括中日韩文字
hasCJKLanguage = true
weight = 2
# 默认每页列表显示的文章数目
paginate = 12
# 版权描述，仅仅用于 SEO
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

# 作者配置
[author]
  name = "bdsdc"

# 菜单配置
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = "道草站点"
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
 
  [[menu.main]]
    identifier = "trader"
    pre = ""
    post = ""
    name = "交易"
    url = "/categories/harmonic-trading"
    title = "交易为生"
    weight = 4
  [[menu.main]]
    identifier = "导航"
    pre = ""
    post = ""
    name = "导航"
    url = "https://dao.bdser.cc"
    title = "我的导航"
    weight = 6
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "about"
    url = "/about/"
    title = "关于我的介绍"
    weight = 5
# Markup related configuration in Hugo
# Hugo 解析文档的配置

# Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
# 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
[highlight]
  codeFences = true
  guessSyntax = true
  lineNos = true
  lineNumbersInTable = true
  # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
  # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
  noClasses = false
# Goldmark is from Hugo 0.60 the default library used for Markdown
# Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
[goldmark]
  [goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [goldmark.renderer]
    # whether to use HTML tags directly in the document
    # 是否在文档中直接使用 HTML 标签
    unsafe = true
  [goldmark.extensions.passthrough]
    enable = true
  [goldmark.extensions.passthrough.delimiters]
    block = [['\[', '\]'], ['$$', '$$']]
    inline = [['\(', '\)']]

# Table Of Contents settings
# 目录设置
[tableOfContents]
  startLevel = 2
  endLevel = 6

[params.header.title]
# URL of the LOGO
# LOGO 的 URL
logo = ""
# title name
# 标题名称
name = "道草站点"
# you can add extra information before the name (HTML format is supported), such as icons
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = ""
# you can add extra information after the name (HTML format is supported), such as icons
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
# whether to use typeit animation for title name
# 是否为标题显示打字机动画
typeit = false

[params.social]
  GitHub = "bdsdc"
  Twitter = "bdstravel22"
  Weibo = "https://weibo.com/u/6214332021"
  RSS = true
    
[params]
  # 网站默认主题样式 ["auto", "light", "dark"]
  defaultTheme = "auto"
  # 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
  gitRepo = ""
  # LoveIt 新增 | 0.1.1 哪种哈希函数用来 SRI, 为空时表示不使用 SRI
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint = ""
  # LoveIt 新增 | 0.2.0 日期格式
  dateFormat = "2006-01-02"
  # 网站标题, 用于 Open Graph 和 Twitter Cards
  title = "我的网站"
  # 网站描述, 用于 RSS, SEO, Open Graph 和 Twitter Cards
  description = "一个小村青年的记录网站"
  # 网站图片, 用于 Open Graph 和 Twitter Cards
  images = ["/logo.png"]
# 主页配置
  [params.home]
    # LoveIt 新增 | 0.2.0 RSS 文章数目
    rss = 10
    # 主页个人信息
    [params.home.profile]
      enable = true
      # Gravatar 邮箱，用于优先在主页显示的头像
      gravatarEmail = ""
      # 主页显示头像的 URL
      avatarURL = "https://bdsblog.oss-cn-shanghai.aliyuncs.com/blog/android-chrome-192x192.png"
      # LoveIt 更改 | 0.2.7 主页显示的网站标题 (支持 HTML 格式)
      title = "交易之路，道阻且长"
      # 主页显示的网站副标题 (允许 HTML 格式)
      subtitle = "这是我的道草｜网站"
      # 是否为副标题显示打字机动画
      typeit = true
      # 是否显示社交账号
      social = true
      # LoveIt 新增 | 0.2.0 免责声明 (支持 HTML 格式)
      disclaimer = ""
    # 主页文章列表
    [params.home.posts]
      enable = true
      # 主页每页显示文章数量
      paginate = 8
      # LoveIt 删除 | 0.2.0 被 params.page 中的 hiddenFromHomePage 替代
      # 当你没有在文章前置参数中设置 "hiddenFromHomePage" 时的默认行为
      defaultHiddenFromHomePage = false

  # 页面底部信息配置
  [params.footer]
    enable = true
    # LoveIt 新增 | 0.2.0 自定义内容 (支持 HTML 格式)
    custom = ''
    # LoveIt 新增 | 0.2.0 是否显示 Hugo 和主题信息
    hugo = true
    # LoveIt 新增 | 0.2.0 是否显示版权信息
    copyright = true
    # LoveIt 新增 | 0.2.0 是否显示作者
    author = true
    # 网站创立年份
    since = 2019
    # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
    icp = ""
    # 许可协议信息 (支持 HTML 格式)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # LoveIt 新增 | 0.2.0 Section (所有文章) 页面配置
  [params.section]
    # section 页面每页显示文章数量
    paginate = 20
    # 日期格式 (月和日)
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 10

  # LoveIt 新增 | 0.2.0 List (目录或标签) 页面配置
  [params.list]
    # list 页面每页显示文章数量
    paginate = 20
    # 日期格式 (月和日)
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 10

  # LoveIt 新增 | 0.2.0 应用图标配置
  [params.app]
    # 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
    title = "我的网站"
    # 是否隐藏网站图标资源链接
    noFavicon = false
    # 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
    svgFavicon = ""
    # Android 浏览器主题色
    themeColor = "#ffffff"
    # Safari 图标颜色
    iconColor = "#5bbad5"
    # Windows v8-10磁贴颜色
    tileColor = "#da532c"
 # Compatibility config
[params.seo]
    # 图片 URL
    image = ""
    # 缩略图 URL
    thumbnailUrl = ""
    # DoIt 新增 | 0.4.1
    # Google 搜索结果中网站备用名字
    alternateName = ["Hugo DoIt"]

  # DoIt 新增 | 0.2.0 网站分析配置
  [params.analytics]
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = ""
      # 是否匿名化用户 IP
      anonymizeIP = true
    # Fathom Analytics
    [params.analytics.fathom]
      id = ""
      # 自行托管追踪器时的主机路径
      server = ""
    # DoIt 新增 | 0.2.13 Baidu Analytics
    [params.analytics.baidu]
      id = ""
    # DoIt 新增 | 0.2.13 Umami Analytics
    [params.analytics.umami]
      data_website_id = "ae183bd6-8277-46d7-99cc-bdaab53a35da"
      src = "https://cloud.umami.is/script.js"
      data_host_url = ""
      data_domains = ""

[params.page]
    # DoIt 新增 | 0.2.0 是否在主页隐藏一篇文章
    hiddenFromHomePage = false
    # DoIt 新增 | 0.2.0 是否在搜索结果中隐藏一篇文章
    hiddenFromSearch = false
    # DoIt 新增 | 0.2.0 是否使用 twemoji
    twemoji = false
    # 是否使用 lightgallery
    lightgallery = false
    # DoIt 新增 | 0.2.0 是否使用 ruby 扩展语法
    ruby = true
    # DoIt 新增 | 0.2.0 是否使用 fraction 扩展语法
    fraction = true
    # 是否在文章页面显示原始 Markdown 文档链接
    linkToMarkdown = true
    # DoIt 新增 | 0.2.14 配置文章原始文件的链接
    linkToSource = false
    # "https://github.com/user/repo/blob/main/{path}"
    # DoIt 新增 | 0.2.13 配置编辑文章的链接
    linkToEdit = false
    # "https://github.com/user/repo/edit/main/{path}"
    # "https://gitlab.com/user/repo/-/edit/main/{path}"
    # "https://bitbucket.org/user/repo/src/main/{path}?mode=edit"
    # DoIt 新增 | 0.2.14 配置提交错误的链接
    linkToReport = false
    # "https://github.com/user/repo/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/user/repo/blob/main/{path}|"
    # DoIt 新增 | 0.2.4 是否在 RSS 中显示全文内容
    rssFullText = false
    # DoIt 新增 | 0.2.13 是否在文章开头显示系列导航
    seriesNavigation = true
    # 是否启用最后修改时间
    enableLastMod = true
    # 是否启用字数统计
    enableWordCount = true
    # 是否启用阅读时间估计
    enableReadingTime = true
    # DoIt 新增 | 0.2.13 过时文章提示
    [params.page.outdatedArticleReminder]
      enable = true
      # 如果文章最后更新于 90 天之前，显示提醒
      reminder = 90
      # 如果文章最后更新于 180 天之前，显示警告
      warning = 180
    # DoIt 新增 | 0.2.0 目录配置
    [params.page.toc]
      # 是否使用目录
      enable = true
      # DoIt 新增 | 0.2.9 是否保持使用文章前面的静态目录
      keepStatic = false
      # 是否使侧边目录自动折叠展开
      auto = true
    # DoIt 新增 | 0.2.0 代码配置
    [params.page.code]
      # 默认展开显示的代码行数
      maxShownLines = 10
    # DoIt 新增 | 0.2.14 表格配置
    [params.page.table]
      # 是否开启表格排序
      sort = true
    # DoIt 更改 | 0.2.0 KaTeX 数学公式
    [params.page.math]
      enable = true
      # 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # 默认行内定界符是 $ ... $ 和 \\( ... \\)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # KaTeX 插件 copy_tex
      copyTex = true
      # KaTeX 插件 mhchem
      mhchem = true
      # 使用 MathJax 替代 KaTeX
      mathjax = false
    # DoIt 新增 | 0.2.0 Mapbox GL JS 配置
    [params.page.mapbox]
      # Mapbox GL JS 的 access token
      accessToken = ""
      # 浅色主题的地图样式
      lightStyle = "mapbox://styles/mapbox/light-v9"
      # 深色主题的地图样式
      darkStyle = "mapbox://styles/mapbox/dark-v9"
      # 是否添加 NavigationControl
      navigation = true
      # 是否添加 GeolocateControl
      geolocate = true
      # 是否添加 ScaleControl
      scale = true
      # 是否添加 FullscreenControl
      fullscreen = true
    # DoIt 更改 | 0.2.0 文章页面的分享信息设置
    [params.page.share]
      enable = true
      Twitter = true
      Evernote = true
      Weibo = true
    # instant.page 设置
    [params.page.instantpage]
      enable = false


[params.search]
  enable = true
  # 搜索引擎的类型 ("algolia", "fuse")
  type = "fuse"
  # 文章内容最长索引长度
  contentLength = 4000
  # 搜索框的占位提示语
  placeholder = ""
  # DoIt 新增 | 0.2.1 最大结果数目
  maxResultLength = 10
  # DoIt 新增 | 0.2.3 结果内容片段长度
  snippetLength = 50
  # DoIt 新增 | 0.2.1 搜索结果中高亮部分的 HTML 标签
  highlightTag = "em"
  # DoIt 新增 | 0.2.4 是否在搜索索引中使用基于 baseURL 的绝对路径
  absoluteURL = false
  [params.search.algolia]
    index = ""
    appID = ""
    searchKey = ""
  [params.search.fuse]
    # DoIt 新增 | 0.2.12 https://fusejs.io/api/options.html
    isCaseSensitive = false
    minMatchCharLength = 2
    findAllMatches = false
    location = 0
    threshold = 0.3
    distance = 100
    ignoreLocation = false
    useExtendedSearch = false
    ignoreFieldNorm = false


# 兼容性设置
[params.compatibility]
# whether to use Polyfill.io to be compatible with older browsers
# 是否使用 Polyfill.io 来兼容旧式浏览器
polyfill = false
# whether to use object-fit-images to be compatible with older browsers
# 是否使用 object-fit-images 来兼容旧式浏览器
objectFit = false



# 用于输出 Markdown 格式文档的设置
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# 用于 Hugo 输出文档的设置
[outputs]
  # DoIt 更改 | 0.2.0
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

# 用于分类的设置
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
series = "series"

